[tool.poetry]
name = "ores"
version = "0.1.0"
description = ""
authors = ["Wyatt Ferguson <wyattf@gmail.com>"]
license = "MIT"
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.12"
pyxel = "^2.2.7"
ruff = "^0.7.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
